INTERVIEW_QUESTIONS = [
    "What is Python and what are its key features?",
    "How do you declare a variable in Python?",
    "What are the basic data types in Python?",
    "What is a list in Python? How do you create one?",
    "How do you add and remove elements from a list?",
    "What is a tuple? How is it different from a list?",
    "What is a dictionary in Python? Give an example.",
    "How do you access values in a dictionary?",
    "What is a set in Python?",
    "How do you create a function in Python?",
    "What is the difference between a function and a method?",
    "How do you pass arguments to a function?",
    "What is a default argument in a function?",
    "What is a keyword argument?",
    "What is *args and **kwargs?",
    "How do you return a value from a function?",
    "What is scope in Python?",
    "What is a global variable?",
    "What is a local variable?",
    "What is the difference between global and local variables?",
    "What is a lambda function?",
    "How do you use list comprehensions?",
    "What is slicing in Python?",
    "How do you reverse a list?",
    "How do you sort a list?",
    "What is the difference between append() and extend()?",
    "How do you copy a list?",
    "What is the difference between shallow copy and deep copy?",
    "What is a string in Python?",
    "How do you concatenate strings?",
    "How do you format strings in Python?",
    "What is f-string?",
    "How do you find the length of a string?",
    "How do you convert a string to uppercase or lowercase?",
    "How do you split a string?",
    "How do you join a list of strings?",
    "What is a module in Python?",
    "How do you import a module?",
    "What is the difference between import and from-import?",
    "What is the standard library?",
    "What is pip?",
    "How do you install a package using pip?",
    "What is a virtual environment?",
    "How do you create and activate a virtual environment?",
    "What is an exception?",
    "How do you handle exceptions in Python?",
    "What is try-except block?",
    "What is finally block?",
    "How do you raise an exception?",
    "What is the difference between SyntaxError and Exception?",
    "What is file handling?",
    "How do you open a file in Python?",
    "How do you read from and write to a file?",
    "What is the with statement in file handling?",
    "How do you check if a file exists?",
    "What is object-oriented programming (OOP)?",
    "What is a class?",
    "How do you create an object?",
    "What is the __init__ method?",
    "What is self in Python classes?",
    "What is inheritance?",
    "What is method overriding?",
    "What is encapsulation?",
    "What is polymorphism?",
    "What is a static method?",
    "What is a class method?",
    "What is the difference between @staticmethod and @classmethod?",
    "What is multiple inheritance?",
    "What is super()?",
    "What is a property in Python?",
    "What is a generator?",
    "How do you create a generator function?",
    "What is yield?",
    "What is an iterator?",
    "How do you create an iterator?",
    "What is the difference between iterator and iterable?",
    "What is a decorator?",
    "How do you write a simple decorator?",
    "What is a context manager?",
    "How do you create a custom context manager?",
    "What is the use of the 'with' statement?",
    "What is the difference between == and is?",
    "What is None in Python?",
    "How do you check if a variable is None?",
    "What is the difference between break, continue, and pass?",
    "How do you write a for loop in Python?",
    "How do you write a while loop in Python?",
    "What is list unpacking?",
    "What is dictionary unpacking?",
    "What is a comprehension?",
    "What is the difference between map, filter, and reduce?",
    "What is a lambda function?",
    "What is the purpose of the __name__ == '__main__' check?",
    "How do you use assertions in Python?",
    "What is unittest?",
    "How do you write a simple test case?",
    "What is docstring?",
    "How do you document a function?",
    "What is PEP8?",
    "What are some common PEP8 guidelines?",
    "What is a package in Python?",
    "How do you create a package?",
    "What is __pycache__?",
    "What is the difference between Python 2 and Python 3?",
    "What is type hinting?",
    "How do you use type hints in Python?",
    "What is a set comprehension?",
    "What is a frozenset?",
    "What is the difference between remove() and pop() in lists?",
    "How do you merge two dictionaries?"
] 